/* Copyright 2026 Sand Harbor Software, LLC. Licensed under the Apache License, Version 2.0. */

import { coreConceptIds as id } from '../../ids.js';
import { conceptLink as link, conceptText as text, defineMeadowConcept as define } from '../../language.js';

export const bundleSource = define({
  id: id.source, name: 'Source', aliases: ['Multi-source Support'], kind: 'entity', searchFacet: true,
  appAreaIds: [id.bundleSourcing, id.bundles],
  definition: text`A named directory admitted to one bundle's graph, with a stable identity, a local location, and optional aliases.`,
  mechanics: [
    text`Source-qualified locations in the editor use name://path so source names cannot be mistaken for folders. A source root is name://. Selected-node details show the folder above the traversal path, qualifying it when the bundle has multiple sources; a single-source bundle shows the relative folder, or / for its root. A separately labeled Source field or column uses the canonical name directly. These readable locations do not change stored node identities or published routes.`,
    text`A source need not be a repository or a vault. A bundle owns its registry and ignored-source decisions; parsed-file caches can be reused without sharing mutable bundle configuration. Canonical names and aliases are unambiguous, and physical roots cannot overlap. Renaming preserves the source identity and retains the old name as an alias; relocation changes only its local location. File and folder identities pair that source identity with their relative paths. Durable bundle-node IDs survive accepted moves.`,
    text`Unqualified links stay within their referring source. Native wikilinks qualify a target as [[Overview::research]], and Markdown or HTML/SVG use source://research/Overview.md. Qualification selects a source before ordinary resolution. Cross-source links consume ordinary traversal budgets, and incoming links can arrive from any configured source. Registering a source does not add a starting selection.`,
    text`Unknown source references remain unresolved diagnostics. Normal-boundary referring pages can prompt Review sources; frontier-only or unrelated pages cannot. Bundle-local ignores durably suppress notices for that name, including future references, without resolving links. Manage sources retains ignored references for reconsideration. Display filters never change diagnostic eligibility. An inaccessible configured source is disconnected, not evidence of deletion.`,
    text`Manage sources registers, renames, reconnects, relocates, or deliberately removes a source. Save compares the proposed material with the accepted snapshot. If no files, moves, or orphaned configuration need review, it applies the settings with unchanged material, closes source management, and reports Sources updated. Otherwise it opens source review, keeping the proposed settings and material pending together. Later preserves that proposal: reopening Manage sources restores its sources and starting selections, while curation and generation continue using accepted material. Changes awaiting review opens the pending review without refreshing or accepting it; further form edits must be saved to update the review. Cancelling the proposal restores accepted settings in source management. A compact summary shows only changed sources above the affected files, with explicit addition, removal, rename, and location-change labels; unchanged sources are omitted. Removal reviews affected configuration through ordinary orphan cleanup, with optional Keep in config retention. Source files are untouched. Removing a required starting selection needs explicit repair; re-registering a removed directory does not restore discarded configuration.`,
  ],
  interplay: text`A ${link(id.sourceSnapshot, 'Source Snapshot')} captures its registry so historical and proposed graphs retain their meaning. Source edits that change included material or require configuration cleanup enter review before changing accepted curation. ${link(id.startingSelection, 'Starting Selections')} independently determine where traversal begins.`,
});

export const sourceSnapshot = define({
  id: id.sourceSnapshot, name: 'Source Snapshot', kind: 'artifact', searchFacet: true, appAreaIds: [id.bundleSourcing],
  definition: text`An immutable capture of source files, assets, and graph context that a bundle can accept as its source material.`,
  mechanics: [
    text`Initial capture records available source material without tracking candidate pages beyond the bundle’s required starting configuration. Later source acceptance passes its snapshot identity and reviewed additions to curation as a bounded bulk tracking request. Track non-sensitive added pages is a bundle preference saved on acceptance; turning it off leaves additions untracked, and later reviews reuse that choice. Source acceptance includes sensitive pages; curation owns the decision to track them. Source review can show curation’s assessment of direct and filter-derived sensitivity. Existing untracked or blacklisted pages and rejected rename matches retain their separate curation decisions.`,
    text`Untracked files that leave the candidate snapshot are shown as No longer included. Absence from a snapshot does not establish filesystem deletion. Tracked entries that leave the working graph are reviewed as orphaned configuration.`,
    text`Capture and acceptance are distinct events. Background discovery retains a candidate while curation and generation continue using the accepted snapshot. Source changes reviews the proposed update, including link directions and depth details from the candidate snapshot’s traversal. Accepted and candidate path details use their respective captured sources with the current saved traversal settings; opening details never substitutes the live source or the Selection graph. Source snapshots separately lists accepted history and marks the current snapshot. Opening history does not refresh or accept sources. Automatic source checks pause while any modal is open, including preview and source review, and resume on the regular thirty-second schedule after it closes. Explicit Check again remains available in source review. Recheck all source files, available in Source snapshots through the bundle menu, forces a complete index rebuild through the same graph path and proposes changes for normal review; it never accepts them automatically. A failed rebuild preserves the previous index and accepted snapshot and reports failure.`,
    text`Every snapshot owns its source registry and stores files by stable source identity plus relative path. A proposed registry, starting selections, and candidate snapshot are accepted together. Failed capture, stale acceptance, and discarded candidates preserve the accepted registry, graph, and node configuration. Source review offers Cancel source settings changes only for pending settings, using Cancel source removal for a single removal; it explains that current sources and material are kept and source files are untouched. Ordinary file-change reviews offer Later and acceptance without a discard action. Cancelling settings does not undo or permanently ignore external file edits, which future source checks can rediscover. Disconnected directories leave the accepted material available and require reconnect, relocation, or deliberate removal.`,
    text`Included source files and required embedded assets are stored in Git trees on source-history branches in Meadow Home. Unchanged content shares blobs. All accepted snapshots remain retained; only the current unaccepted candidate is retained. Normal checkout and staging are unchanged.`,
    text`Library-wide discovery uses a disposable persistent Source Graph Index owned by the Rust working-graph subsystem. Each request reconciles file modification time, change time, size, and filesystem identity before reusing parsed links and content fingerprints. The index lives under Meadow Home cache/source-index, keyed by a hash of the resolved source directory, shared by bundles and excluded from Git tracking. Accepted source metadata and content remain scoped to the included graph. Expanded trees are disposable caches; historical text comparisons read immutable Git blobs. Backups preserve the repository and its source-history references.`,
  ],
  interplay: text`${link(id.bundleSourcing, 'Sourcing')} owns capture and acceptance; ${link(id.bundleCuration, 'Curation')} selects from the accepted material and ${link(id.bundleGeneration, 'Generation')} consumes it without refreshing live source files. A source snapshot is product data inside a Meadow Home; an acceptance ${link(id.checkpoint, 'Checkpoint')} captures a whole home and is unrelated.`,
  implementationRoles: ['capture', 'accept'] as const,
});

export const sourceMove = define({
  id: id.sourceMove, name: 'Source Move', kind: 'mechanism', searchFacet: true, appAreaIds: [id.bundleSourcing],
  definition: text`A proposed correspondence between a configured page whose source location disappeared and a source file at another location.`,
  mechanics: [text`Content fingerprints and graph context provide inspectable evidence, including moves between configured sources. An accepted cross-source move preserves the durable node ID, tracking, and traversal overrides. Matching names alone cannot establish identity, and competing destinations remain ambiguous. Empty file contents do not establish a file identity match; a missing empty page remains orphaned and a newly discovered empty page remains new. Two independent, unambiguous content matches can establish a shared folder move for related pages whose contents remain highly similar after consistent filename and link rewrites. An uncontested match is proposed as a rename. Competing destinations or identities require an explicit choice before acceptance; neither the UI nor the acceptance API silently selects one. Accepting the source update applies the resolved proposal and preserves identity; Details exposes evidence and an optional correction to treat them as different pages, removing the old orphaned configuration and leaving the new page untracked. Traversal details show the route leading to the page as file pills, without repeating the moved endpoint. An unchanged leading route is shown once; different routes retain Before and After. Content comparison is offered only when captured file contents differ. Proposed matches never assign two configured identities to one destination. Pages in move review are excluded from orphan cleanup and separate added or missing entries.`],
  interplay: text`A missing starting page or selected starting folder requires user-directed repair; discovery reports the missing source and keeps the accepted snapshot without automatically relocating the starting point. Identity proposals for other pages are applied when accepting a ${link(id.sourceSnapshot, 'Source Snapshot')}. A file moved beyond the admitted graph remains an ${link(id.orphan, 'Orphaned Bundle Page')} at its historical locator; discovery does not retain an unrelated destination outside the capture boundary.`,
});

export const sourceChange = define({
  id: id.sourceChange, name: 'Source Change', kind: 'artifact', searchFacet: true, appAreaIds: [id.bundleSourcing],
  definition: text`A named set of simple filesystem operations applied to an isolated fixture source graph for development and acceptance testing.`,
  mechanics: [text`Development controls and automated scenarios share the executor. Each change states its Action and Check separately and names one designated E2E scenario that applies those same operations and verifies the stated outcome. Quickcheck requires a distinct, existing scenario for every change across all fixture menus; other tests may reuse a change as setup. The E2E row links the newest assembled run containing that designated scenario, even when newer runs exercise unrelated scenarios, and says when no run has been recorded. Shared source graphs share this mapping across fixture menus. Its first category gives it one home in the development UI while retaining additional category tags; empty categories stay visible and disabled. Operation previews use name://path for registered source locations, while executable operations retain filesystem-relative paths. Node specs describe concrete states unconditionally. Their sourcing section asserts working graph membership, source links, and frontier/orphan reachability under the bundle’s traversal and blacklist configuration; curation asserts tracking and filter selections; generation asserts rendered HTML links. Each spec lives beside its source node in a file named <full-source-filename>.nodespec.yaml with a nodespecs list, across every supported source node format. A fixture source graph can omit node specs entirely; once any node has one, every source node must have specs for each owning bundle whose declared source set includes it. A nodespec link may name a canonical source; omission means the tested node’s own source. Assertions match source and relative path together, keeping duplicate filenames distinct. Source contents are copied verbatim while node spec files stay in the authoring fixtures; TypeScript scenarios own sequencing and decisions. Start scenario resets the fixture, refreshes and accepts its baseline (including orphan cleanup), applies the selected change, refreshes sources, and opens source review. A scenario that disconnects or relocates a source opens the accepted bundle for repair instead of attempting an impossible capture. Folder relocation checks the complete isolated directory inventory and rolls back if journaling fails. Apply change modifies only the running fixture files, leaving automatic detection and manual refresh observable. Development and E2E compose shared setup primitives backed by Command operations. Opening source review is a navigation destination; it does not refresh or accept material.`],
  interplay: text`Source Changes exercise ${link(id.sourceSnapshot, 'Source Snapshot')} discovery and ${link(id.sourceMove, 'Source Move')} review through normal application behavior. They start from a ${link(id.homeFixture, 'Home Fixture')} and apply to any open ${link(id.savedState, 'Saved State')} that includes their source graph, including a forked ${link(id.checkpoint, 'Checkpoint')}.`,
  implementationRoles: ['apply'] as const,
});

export const orphan = define({
  id: id.orphan, name: 'Orphaned Configuration', aliases: ['Orphan', 'Orphaned Bundle Page', 'Orphaned Bundle Pages'],
  kind: 'state', searchFacet: true, appAreaIds: [id.bundleSourcing],
  definition: text`A non-blacklisted page with durable bundle configuration that is no longer reachable in the working graph of the source snapshot under review.`,
  mechanics: [text`Sourcing reviews the candidate graph when one is available, otherwise the accepted graph. Orphans contribute to the source-review count; possible moves are counted separately once. An orphan appears once in review, without a duplicate missing-file item. Accepting removes eligible orphaned configuration entries by default, including old identities left by rejected rename matches. Individual or bulk Keep in config overrides are optional and reversible before acceptance; explicitly kept orphans remain pending for later review. Source files are retained. Required traversal and collection entries cannot be removed here. Explanations distinguish a still-present link to a filesystem-confirmed missing file from a removed link or a file outside the captured graph. An unavailable source does not establish deletion. File pills identify the affected paths; the full previous route is available under a disclosure.`],
  interplay: text`${link(id.bundleSourcing, 'Sourcing')} owns orphan review together with ${link(id.sourceMove, 'Source Move')} decisions. ${link(id.bundleCuration, 'Curation')} continues to use the accepted graph until the review is applied.`,
});

export const sourcingConcepts = [bundleSource, sourceSnapshot, sourceMove, sourceChange, orphan] as const;
