archivedAt: null
siteGuid: p7s4k9m
sourceDirectory: ./source_graphs/meadow-test-sites-data
siteCreatedAt: 2025-06-02T16:25:00.000Z
siteLastPublishedAt: null
siteNotes: ""
siteUpdatedAt: 2025-06-02T16:25:00.000Z
generatedSiteVersions: []
generationSpacedRepetitionEnabled: true
generationSpacedRepetitionTags:
  - "#t022-srs/beta"
entrySiteNodeId: 8a0338e11ca9
defaultTraversalSiteNodeId: 8a0338e11ca9
