nodes:
  - siteNodeName: t022 - spaced repetition
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 8a0338e11ca9
    listType: whitelist
  - siteNodeName: t022 ---- alpha cards
    sourceGraphSubdirectory: t022
    siteNodeKind: file
    fileType: md
    siteNodeId: 416db9d23105
    listType: whitelist
  - siteNodeName: t022 ---- beta cards
    sourceGraphSubdirectory: t022
    siteNodeKind: file
    fileType: md
    siteNodeId: ce40852ef691
    listType: whitelist
