archivedAt: null
siteGuid: p7s4k9m
defaultTraversalSitePageTitle: t022 - spaced repetition
defaultTraversalSitePageDirectory: ""
sourceDirectory: ./source_graphs/meadow-test-sites-data
initialSitePageTitle: t022 - spaced repetition
initialSitePageDirectory: ""
siteCreatedAt: 2025-06-02T16:25:00.000Z
siteLastPublishedAt: null
siteNotes: ""
siteUpdatedAt: 2025-06-02T16:25:00.000Z
generatedSiteVersions: []
generationSpacedRepetitionEnabled: true
generationSpacedRepetitionTags:
  - "#t022-srs/beta"
