archivedAt: null
bundleCreatedAt: 2025-06-02T16:25:00.000Z
bundleGuid: 8n4c2vp
bundleLastPublishedAt: null
bundleNotes: ""
bundleUpdatedAt: 2025-06-02T16:25:00.000Z
defaultTraversalBundleNodeId: 9199e7df80fa
entryBundleNodeId: 9199e7df80fa
generatedBundleVersions: []
sourceDirectory: ./source_graphs/meadow-test-bundles-data
