archivedAt: null
bundleGuid: 8n4c2vp
sourceDirectory: ./source_graphs/meadow-test-bundles-data
bundleCreatedAt: 2025-06-02T16:25:00.000Z
bundleLastPublishedAt: null
bundleNotes: ""
bundleUpdatedAt: 2025-06-02T16:25:00.000Z
generatedBundleVersions: []
entryBundleNodeId: 9199e7df80fa
defaultTraversalBundleNodeId: 9199e7df80fa
