bundleGuid: fldr001
sourceDirectory: ./source_graphs/folder-structure-test
entryBundleNodeId: 3fef494a5c4d
defaultTraversalBundleNodeId: 3fef494a5c4d
defaultOutlinksDepth: 2
defaultInlinksDepth: 0
generationFolderNavigationEnabled: true
generatedBundleVersions: []
archivedAt: null
bundleCreatedAt: 2026-08-12T20:30:28.078Z
bundleUpdatedAt: 2026-08-12T20:30:28.078Z
bundleLastPublishedAt: null
bundleNotes: ""
