archivedAt: null
siteGuid: q1m9z7c
defaultTraversalSitePageTitle: main page
defaultTraversalSitePageDirectory: ""
sourceDirectory: ./source_graphs/meadow-test-sites-data
initialSitePageTitle: main page
initialSitePageDirectory: ""
siteCreatedAt: 2025-06-02T16:25:00.000Z
siteLastPublishedAt: null
siteNotes: ""
siteUpdatedAt: 2025-06-02T16:25:00.000Z
generatedSiteVersions: []
