bundleGuid: fldr002
sourceDirectory: ./source_graphs/folder-structure-test
entryBundleNodeId: 7e4a79dd2c06
defaultTraversalBundleNodeId: 7e4a79dd2c06
defaultOutlinksDepth: 2
defaultInlinksDepth: 0
generationFolderNavigationEnabled: true
generatedBundleVersions: []
archivedAt: null
bundleCreatedAt: 2026-08-12T20:30:28.893Z
bundleUpdatedAt: 2026-08-12T20:30:28.893Z
bundleLastPublishedAt: null
bundleNotes: ""
