archivedAt: null
siteGuid: 7h3f9kx
defaultTraversalSitePageTitle: V Dwarkesh and Anthropic CEO in 2023
defaultTraversalSitePageDirectory: ai
sourceDirectory: ./source_graphs/meadow-test-site-for-hooks
initialSitePageTitle: V Dwarkesh and Anthropic CEO in 2023
initialSitePageDirectory: ai
siteCreatedAt: 2025-01-07T16:25:00.000Z
siteLastPublishedAt: null
siteNotes: site for testing hooks with markdown processing and page name normalization
siteUpdatedAt: '2025-01-07T16:25:00.000Z'
generatedSiteVersions: []

