archivedAt: null
siteGuid: 7h3f9kx
sourceDirectory: ./source_graphs/meadow-test-site-for-hooks
siteCreatedAt: 2025-01-07T16:25:00.000Z
siteLastPublishedAt: null
siteNotes: site for testing hooks with markdown processing and page name normalization
siteUpdatedAt: 2025-01-07T16:25:00.000Z
generatedSiteVersions: []
defaultOutlinksDepth: 4
entrySiteNodeId: 989eb6ecc274
defaultTraversalSiteNodeId: 989eb6ecc274
