nodes:
  - siteNodeName: t002 - dup pages and images
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 7c1cc857cc2a
    listType: whitelist
  - siteNodeName: t002 ---- dup
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 6f32f146d270
    listType: whitelist
  - siteNodeName: t002 ---- dup
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: png
    siteNodeId: b93a4465213b
    listType: whitelist
  - siteNodeName: t002 ---- dup
    sourceGraphSubdirectory: t002
    siteNodeKind: file
    fileType: md
    siteNodeId: b14e056ec2b8
    listType: whitelist
  - siteNodeName: t002 ---- dup
    sourceGraphSubdirectory: t002
    siteNodeKind: file
    fileType: png
    siteNodeId: 20e02153f864
    listType: whitelist
  - siteNodeName: t002 ---- dup
    sourceGraphSubdirectory: t002/extra nested
    siteNodeKind: file
    fileType: md
    siteNodeId: "663926718e65"
    listType: whitelist
  - siteNodeName: t002 ---- dup 2
    sourceGraphSubdirectory: t002
    siteNodeKind: file
    fileType: png
    siteNodeId: 0e86bf751453
    listType: whitelist
  - siteNodeName: t002 ---- dup 2
    sourceGraphSubdirectory: t002/extra nested
    siteNodeKind: file
    fileType: png
    siteNodeId: 3fec7f72f0fa
    listType: whitelist
  - siteNodeName: t002 ---- points to extra nested dup
    sourceGraphSubdirectory: t002
    siteNodeKind: file
    fileType: md
    siteNodeId: "770382996259"
    listType: whitelist
  - siteNodeName: t002 ---- points to nested dup
    sourceGraphSubdirectory: t002
    siteNodeKind: file
    fileType: md
    siteNodeId: 2b63ed731f64
    listType: whitelist
  - siteNodeName: t002 ---- points to nested png dup
    sourceGraphSubdirectory: t002
    siteNodeKind: file
    fileType: md
    siteNodeId: f77f7ad11d54
    listType: whitelist
  - siteNodeName: t002 ---- points to png dup 2 with no path from extra nested
    sourceGraphSubdirectory: t002/extra nested
    siteNodeKind: file
    fileType: md
    siteNodeId: 5b1158d75da6
    listType: whitelist
  - siteNodeName: t002 ---- points to png dup 2 with no path from root
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 71e9466cc461
    listType: whitelist
  - siteNodeName: t002 ---- points to png dup 2 with no path from second directory
    sourceGraphSubdirectory: t002 - second directory
    siteNodeKind: file
    fileType: md
    siteNodeId: 9392a96a77ca
    listType: whitelist
  - siteNodeName: t002 ---- points to png dup 2 with no path from t002
    sourceGraphSubdirectory: t002
    siteNodeKind: file
    fileType: md
    siteNodeId: da6f6f8f1f43
    listType: whitelist
  - siteNodeName: t002 ---- points to root dup
    sourceGraphSubdirectory: t002
    siteNodeKind: file
    fileType: md
    siteNodeId: bb3ad5f67a36
    listType: whitelist
  - siteNodeName: t002 ---- points to root png dup
    sourceGraphSubdirectory: t002
    siteNodeKind: file
    fileType: md
    siteNodeId: 23293509ade7
    listType: whitelist
