archivedAt: null
siteGuid: 4k7s0hd
sourceDirectory: ./source_graphs/meadow-test-sites-data
siteCreatedAt: 2025-06-02T16:25:00.000Z
siteLastPublishedAt: null
siteNotes: nested initial page, in link depth of one, hooks for html generation
siteUpdatedAt: 2025-12-14T17:34:47.908Z
generatedSiteVersions: []
defaultOutlinksDepth: 4
defaultInlinksDepth: 1
entrySiteNodeId: 5b1158d75da6
defaultTraversalSiteNodeId: 5b1158d75da6
