nodes:
  - siteNodeName: 2026-02-02
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: c0b3baeaf879
    listType: blacklist
  - siteNodeName: Charlie Munger
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 0f8db8808fcd
    listType: whitelist
  - siteNodeName: Circle of Competence
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: fe1577b870ca
    listType: whitelist
  - siteNodeName: Cognitive Biases
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 39145d165089
    listType: whitelist
    outlinksDepth: 0
  - siteNodeName: First Principles Thinking
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 04eda3a5b117
    listType: whitelist
  - siteNodeName: Hanlon's Razor
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 2003293f5ea8
    listType: whitelist
  - siteNodeName: Howard Marks
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: dbc8dee79f6c
    listType: whitelist
  - siteNodeName: Inversion
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 12d450f2d870
    listType: whitelist
  - siteNodeName: Latticework of Mental Models
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 8da3c4d1d4b6
    listType: whitelist
  - siteNodeName: Man with a Hammer
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: c9dbd298c894
    listType: whitelist
  - siteNodeName: Margin of Safety
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 74bda59575a8
    listType: whitelist
  - siteNodeName: Mental Models Diagram
    sourceGraphSubdirectory: images
    siteNodeKind: file
    fileType: svg
    siteNodeId: 0828268017f6
    listType: whitelist
  - siteNodeName: Mental Models Overview
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: d2a063bedab9
    listType: whitelist
  - siteNodeName: Notable Mental Models
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 7fe9ab3fa811
    listType: whitelist
  - siteNodeName: Occam's Razor
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: d40772aab5c5
    listType: whitelist
  - siteNodeName: Probabilistic Thinking
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 644a5e8e09c4
    listType: whitelist
  - siteNodeName: Razors
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 91f3e10a54aa
    listType: whitelist
  - siteNodeName: Second Order Thinking
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: fa497d93b1fd
    listType: whitelist
  - siteNodeName: Warren Buffett
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: fc2dea7624f6
    listType: whitelist
