nodes:
  - siteNodeName: Alpha
    sourceGraphSubdirectory: Alpha
    siteNodeKind: folder
    siteNodeId: f21b53e6bbbd
    listType: whitelist
  - siteNodeName: Beta
    sourceGraphSubdirectory: Beta
    siteNodeKind: folder
    siteNodeId: b2db90165ec0
    listType: whitelist
  - siteNodeName: Ordered Folders
    siteNodeKind: collection
    siteNodeId: 7e4a79dd2c06
    listType: whitelist
    memberSiteNodeIds:
      - b2db90165ec0
      - f21b53e6bbbd
