/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MeadowPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var fs = __toESM(require("fs"), 1);
var os = __toESM(require("os"), 1);
var DEFAULT_SETTINGS = {};
var MeadowPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "open-in-meadow",
      name: "Open in meadow",
      editorCallback: (editor, view) => {
        this.openInMeadow(view.file);
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("Open in Meadow").setIcon("external-link").onClick(() => {
              this.openInMeadow(file);
            });
          });
        }
      })
    );
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  openInMeadow(file) {
    var _a;
    console.log("=== Meadow Plugin: openInMeadow called ===");
    if (!file) {
      console.log("Meadow Plugin: No file selected, returning early");
      new import_obsidian.Notice("No file selected");
      return;
    }
    console.log("Meadow Plugin: File info:", {
      name: file.name,
      path: file.path,
      basename: file.basename,
      extension: file.extension
    });
    const vaultPath = this.app.vault.adapter.basePath;
    console.log("Meadow Plugin: Vault path:", vaultPath);
    const folderPath = ((_a = file.parent) == null ? void 0 : _a.path) || "";
    console.log("Meadow Plugin: Folder path within vault:", folderPath);
    const pageName = file.basename;
    console.log("Meadow Plugin: Page name:", pageName);
    const args = [
      "--vault-path",
      vaultPath,
      "--folder-path",
      folderPath,
      "--page-name",
      pageName
    ];
    console.log("Meadow Plugin: Arguments to pass:", args);
    console.log("Meadow Plugin: Full command will be: open -a Meadow --args", args.join(" "));
    try {
      const possiblePaths = [
        "/Applications/Meadow.app",
        `${os.homedir()}/Applications/Meadow.app`,
        "Meadow.app"
      ];
      let appPath = "Meadow";
      for (const path of possiblePaths) {
        console.log("Meadow Plugin: Checking if app exists at:", path);
        if (fs.existsSync(path)) {
          appPath = path;
          console.log("Meadow Plugin: Found Meadow.app at:", appPath);
          break;
        }
      }
      console.log(`Meadow Plugin: Final command will be: open -a ${appPath} --args ${args.join(" ")}`);
      const process = (0, import_child_process.spawn)("open", ["-a", appPath, "--args", ...args], {
        stdio: "inherit",
        detached: true
      });
      console.log("Meadow Plugin: Spawn process created with PID:", process.pid);
      console.log("Meadow Plugin: Process spawn options:", {
        stdio: "inherit",
        detached: true
      });
      setTimeout(() => {
        console.log("Meadow Plugin: Attempting to bring Meadow to front...");
        (0, import_child_process.spawn)("osascript", ["-e", 'tell application "Meadow" to activate'], {
          stdio: "inherit",
          detached: true
        }).unref();
      }, 1e3);
      process.on("error", (error) => {
        console.error("Meadow Plugin: Process error event:", error);
      });
      process.on("exit", (code, signal) => {
        console.log("Meadow Plugin: Process exit event - code:", code, "signal:", signal);
      });
      process.unref();
      console.log("Meadow Plugin: Process unref() called, detaching from parent");
      new import_obsidian.Notice(`Opening ${pageName} in Meadow...`);
      console.log("Meadow Plugin: Notice displayed to user");
    } catch (error) {
      console.error("Meadow Plugin: Error spawning process:", error);
      new import_obsidian.Notice(`Failed to open Meadow: ${error}`);
    }
    console.log("=== Meadow Plugin: openInMeadow completed ===");
  }
};
