archivedAt: null
bundleGuid: 7h3f9kx
sourceDirectory: ./source_graphs/meadow-test-bundle-for-hooks
bundleCreatedAt: 2025-01-07T16:25:00.000Z
bundleLastPublishedAt: null
bundleNotes: bundle for testing hooks with markdown processing and page name normalization
bundleUpdatedAt: 2025-01-07T16:25:00.000Z
generatedBundleVersions: []
defaultOutlinksDepth: 4
entryBundleNodeId: 989eb6ecc274
defaultTraversalBundleNodeId: 989eb6ecc274
