nodes:
  - siteNodeName: t001 - deeply nested
    sourceGraphSubdirectory: ""
    siteNodeKind: file
    fileType: md
    siteNodeId: 9199e7df80fa
    listType: whitelist
  - siteNodeName: t001 ---- child 1
    sourceGraphSubdirectory: t001
    siteNodeKind: file
    fileType: md
    siteNodeId: def2182907d1
    listType: whitelist
  - siteNodeName: t001 ---- child 2
    sourceGraphSubdirectory: t001/deeper
    siteNodeKind: file
    fileType: md
    siteNodeId: 729081fe7312
    listType: whitelist
