archivedAt: null
siteGuid: 8n4c2vp
sourceDirectory: ./source_graphs/meadow-test-sites-data
siteCreatedAt: 2025-06-02T16:25:00.000Z
siteLastPublishedAt: null
siteNotes: ""
siteUpdatedAt: 2025-06-02T16:25:00.000Z
generatedSiteVersions: []
entrySiteNodeId: 9199e7df80fa
defaultTraversalSiteNodeId: 9199e7df80fa
