archivedAt: null
bundleGuid: q1m9z7c
sourceDirectory: ./source_graphs/meadow-test-bundles-data
publishSlug: meadow-test-bundle-big
bundleCreatedAt: 2025-06-02T16:25:00.000Z
bundleLastPublishedAt: null
bundleNotes: ""
bundleUpdatedAt: 2025-06-02T16:25:00.000Z
generatedBundleVersions: []
defaultOutlinksDepth: 4
defaultInlinksDepth: 100
entryBundleNodeId: ef63f962db68
defaultTraversalBundleNodeId: ef63f962db68
